### ISSUE TITLE
Add section_4 to module article page format

### ISSUE THREAD

**Issue by lauriemarkle** [ParentingForLifelongHealth/plh-kids-app-kw-content#24]
When creating content for ParentApp kids KW it became clear that we will need 4, not 3, sections within article template. I've created the structure in the data list and in relevant docs. Content is synced. The template & design need updated to match this. 
Thanks!

**Comment by esmeetewinkel** [comment]
Looks like this is working already :) 

![image](https://github.com/user-attachments/assets/c26b59e3-041c-4b5b-86f6-b7a476cc57c1)
