### ISSUE TITLE
Learning Through Play Activity

### ISSUE THREAD

**Issue by lauriemarkle** [ParentingForLifelongHealth/plh-kids-app-kw-content#41]
The selected incentives for caregivers to engage with the app are playful activities. 
A selection of 44 playful activities for parents to complete with their child will be created as videos. 

Parents will “unlock” a new video after completing each module and/or home activity report. 

Upon completing the final home activity report, participants will unlock access to all the playful activities, instead of receiving just one as a reward.

The library will allow parents to “heart” or “favorite” the activities they want to come back to.

They should be able to filter their view to their favorite activities and child age range. 

Activities will NOT be filtered by activity type (quick, calm, for a group, active, etc).

We need a data list that contains: 
activity_id, activity_name, activity_ages, asset file name, transcript, attribution. 

Attribution will be a text-only field that should read mark-down, allowing us to indicate the source of the activity with a hyperlink to the initial source, if relevant.

**Comment by esmeetewinkel** [comment]
[Sheet](https://docs.google.com/spreadsheets/d/1o0mIixujxvgrJMN5xRhIJbO-Ku2OY4rfgg3AOq-LnAM)
[Doc](https://docs.google.com/document/d/1GiePRd8Qk_TEKcQXjR__v2O5SQBw_dOeU-5gOOIfpT0)

**Comment by esmeetewinkel** [comment]
Mostly closed by #89, still need to enable filtering by child age range
