### ISSUE TITLE
Check-In Data List Expansion

### ISSUE THREAD

**Issue by lauriemarkle** [ParentingForLifelongHealth/plh-kids-app-kw-content#54]
The current data list for wellbeing check-in allows for just 3 emotions. The list should be expanded to offer up to 6 with feedback.

**Comment by esmeetewinkel** [comment]
Done, see https://docs.google.com/spreadsheets/d/1gCaE-fGiTAE8rIZNnUItm79CkCBhmvMClnpOzYGqdPI/edit?gid=367260570#gid=367260570

![image](https://github.com/user-attachments/assets/15cc96da-9678-4c7d-959d-2c6367c35dfc)
