### ISSUE TITLE
List globals in new design

### ISSUE THREAD

**Issue by esmeetewinkel** [ParentingForLifelongHealth/plh-kids-app-kw-content#61]
Create a list of all strings that appear in Faith's design and are not coming from a data list. This can be a list of global variables. This is needed to send off to translators.

**Comment by FaithDaka** [comment]
@esmeetewinkel Here's the list: [Doc](https://docs.google.com/document/d/1gQqVGH8S9D4Uv1__gw4GjBvGdGnSQMSXvVWnwUG-xW0/edit?usp=sharing)

**Comment by esmeetewinkel** [comment]
Thanks @FaithDaka. Made available in the app as global variables [here](https://docs.google.com/spreadsheets/d/1SleWGZ0N9RhaLQl1qSzchftghNEG0EsoTkIV1W9p-x0/edit?gid=2022662819#gid=2022662819).
