### ISSUE TITLE
Onboarding / Intro Flow

### ISSUE THREAD

**Issue by lauriemarkle** [ParentingForLifelongHealth/plh-kids-app-kw-content#78]
After parents receive consent, on the screen where they are asked their name and gender, they should also answer the question, "I am a..."
and then select from a drop-down menu
- Parent or Caregiver
- Facilitator
- System Tester

so that we can separate user data later on.

**Comment by esmeetewinkel** [comment]
The navigation flow is currently
1. Language select
2. Consent to terms and conditions 

This will need additional steps 
3. Identify as caregiver / facilitator / tester (as described above)
4. Login #53

**Comment by esmeetewinkel** [comment]
Closed by https://github.com/ParentingForLifelongHealth/plh-kids-app-kw-content/pull/81
