### ISSUE TITLE
Change to In-Module Design for Kuwait

### ISSUE THREAD

**Issue by lauriemarkle** [ParentingForLifelongHealth/plh-kids-app-kw-content#8]
Refer to Figma for design. 

**Home Screen Tasks**
Home Screen contains tasks for the day, including any incomplete home activity reporting + the earliest unfinished module. 
Home activity reporting is assigned for each incomplete report for every module completed prior to midnight of the previous day. 
Home Screen tasks update each night at midnight. 

As tasks are completed, their iconography transforms into a completed tick mark. 

**Home Screen Design**
On the Home Screen, tasks will be displayed as cards. Effort should be made to reduce margins for illustrations and within cards to create ample room for translation. 

Tasks for home activity reporting appear prior to the module task. Cards appearing for the home activity reporting take on the illustration to the parent module. (e.g. home activity reporting for the home assignment/practise given for the One-on-One Time module will have the module illustration for One-on-One Time)

**Home Screen Game Unlock**
Once all assigned daily tasks are completed, the user receives a congratulations message with a trophy/star drop. This overlay screen comes with an X button in the top right to close. 
The home screen appears with a new "Game of the Day" button at the footer of the task list. This button is a dark yellow, corresponding to an action. 

**User Journey / Content Overview Page**
The home page is dedicated to daily tasks, but in the footer, users can navigate to a user journey to see their progress against all app modules. 

The user journey screen shall contain a meandering "map" of modules. Content shall be structured in 2 columns (curved dashed line, either left or right facing, and the module illustration with a circle behind it with the module name underneath). The module illustration will be white in the background if unlocked, accessible, or gray if locked. 

No other iconography or tracking will be visible from this view. 

On the user journey screen, if a user accesses a module, the unassigned home activity review will appear underneath the list of subsections within a module. 

**Module Home Screen**
On Module home screen, content for sub-sections should be locked and in light gray until the preceding content is completed.

**Comment by lauriemarkle** [comment]
When the user has completed ALL modules/sessions & home practise reports in the app, two things happen: 
- The home screen becomes the user journey / map
- All locked games become unlocked

When the final programme task is completed a unique overlay view, congratulating the parent on completing the programme will appear. The template for this overlay should match the templates created for module/session completion. This template should, at a minimum, include: image asset, header text, body text, button text (if left empty, no button appears), button link (either home or to rewards/games)

**Comment by esmeetewinkel** [comment]
@lauriemarkle Closing this as this has been rethought in the Kuwait Sep 2024 workshop and then replaced by @FaithDaka's new designs
